### ISSUE TITLE
Bot crashes after clicking 1

### ISSUE THREAD

**Issue by Szunio** [MrFums/Valbot#18]
After running bot and clicking 1 it crashes. I launched bat file as administrator

**Comment by MrFums** [comment]
That is probably because a package has been installed in correctly. Please either try and get me a crash log or run in idle and tell me the error message.

**Comment by Sk0ipy** [comment]
i have everything installed 4 times, but everytime i click 1 it closes switches to my homescreen and the bot closes

**Comment by MrFums** [comment]
@Szunio @Sk0ipy Possibly fixed in 1.7.4. Please test by downloading it [here](https://github.com/MrFums/Valbot/releases/latest)

**Comment by Sk0ipy** [comment]
@MrFums nope, still not. it still shutsdown. and tabs away valorant. tried everything. but still doesn't work.

**Comment by MrFums** [comment]
Ok, open CMD and type in `pip uninstall numpy` then press `y`. After it has uninstalled run the new bat file again found in releases.

**Comment by Sk0ipy** [comment]
![image](https://user-images.githubusercontent.com/74152292/98550476-70f0bd80-229c-11eb-88f1-e5e58479e75d.png)
it keeps saying this

**Comment by MrFums** [comment]
If you have the crash when you load into the bot script / when you press 1 to begin the bot, you need to uninstall numpy ( pip uninstall numpy ) and install an older version of numpy: pip install numpy==1.19.3

**Comment by Sk0ipy** [comment]
does it really need to be 1.19.3, cause its says this : _### 

> ERROR: Could not find a version that satisfies the requirement numpy==1.19.3 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0b3, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.11.2rc1, 1.11.2, 1.11.3, 1.12.0b1, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1)
> ERROR: No matching distribution found for numpy==1.19.3

_

**Comment by MrFums** [comment]
Reading that image you just sent. It would help if you actually read the read me and you would understand you need python 3.8 for the program to function

**Comment by Sk0ipy** [comment]
everytime i use this command (pip install numpy==1.19.3) he keeps saying this: 
![image](https://user-images.githubusercontent.com/74152292/98558821-2e33e300-22a6-11eb-9336-73316ce806ed.png)
how do i fix this?

**Comment by Sk0ipy** [comment]
nvm i fixed it, i think
